### ISSUE TITLE
Melhorar Alertas para evitar falsos alarmes

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/instore#149]
### Mint
- [x] colocar na TV
- [x] garantir que está funcionando no Android
- [ ] garantir que está funcionando no iOS

### Métricas
- [x] Produto sem estoque
- [x] Busca por produto não cadastrado
- [x] Gerar um Do com essas buscas

### Alerts
- [x] Learn about common critical errors
- [ ] Enhance "Error Report" feature
- [x] Produto sem estoque
- [ ] Error reported by the user

**Comment by guilhermebruzzi** [comment]
Fechar por enquanto pra no futuro revermos melhor os alertas
