### ISSUE TITLE
Valor minimo da compra no carrinho na primeira compra do ciclo

### ISSUE THREAD

**Issue by guilhermebruzzi** [vtex/instore#170]
@marcelocouto Mais alguma informação sobre ciclos tem que estar no inStore? Eu lembro de vc falar alguma coisa sobra usar um saleschannel por vendedor.

Adiciona olhando o trello: https://trello.com/b/vmy8ceoy/eudoravd

**Comment by darlenedms** [comment]
Feito em https://github.com/vtex/checkout-instore/pull/416 e https://github.com/vtex/checkout-instore-custom/pull/1
