### ISSUE TITLE
Adaptar inStore para nova arquitetura de sellers e checkin

### ISSUE THREAD

**Issue by nevescode** [vtex/instore#185]
https://drive.google.com/drive/u/0/folders/0B0YqFzQfpeEpa3ZlQ3BFTDBHdWc

- [ ] Obter política comercial do portal, fazer cache por 30 minutos e usar nas chamadas para as APIs
- [ ] Definir contrato de dados com Logistics e CheckoutAPI
- [ ] Criar novos cenários no robô
- [ ] Alterar ambiente instoreqa pra testar mudanças

**Comment by guilhermebruzzi** [comment]
Vai virar outras issues isso no futuro
