### ISSUE TITLE
Criar nova rota para exibir detalhe de produto no carrinho

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/instore#197]
A pagina do produto deveria ser uma só e se comportar de forma diferente se o produto já está no carrinho ou não.

Ou seja, quando se busca um produto e entra nele, deveria haver uma rota para mostrar detalhes desse produto assim como no carrinho clicar em produto leva para essa mesma rota com detalhes do produto. Hoje temos um modal que sobe na frente no carrinho e algo diferente na busca.

**Comment by guilhermebruzzi** [comment]
Done by @lbebber
