### ISSUE TITLE
Layout desktop (LeskTopper)

### ISSUE THREAD

**Issue by guilhermebruzzi** [vtex/instore#313]

**Comment by gabrielgalc** [comment]
O que falta:
- [ ] Remover animações da sidebar
- [ ] Criar status "selected" na sidebar
- [ ] Botar os botões de navegação pra funcionar
- [ ] Melhorar o Menu

**Comment by gabrielgalc** [comment]
@lbebber vai fazer a animação da navegação das suggestions

**Comment by lbebber** [comment]
Done
