### ISSUE TITLE
Easy setup

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/instore#314]
Easy inStore setup
 - [ ] Criar pagina e template no portal
 - [ ] Criar transportadora inStore no logistic
 - [ ] Pagamentos no gateway (ver homologação da Stone)

**Comment by guilhermebruzzi** [comment]
API para criação dos scripts no Portal V2:

https://github.com/vtex/scaling-disco/blob/master/src/clients/PortalV2.js

**Comment by lowbeer** [comment]
entidade SO criada automaticamente pelo MD nao esta marcando os campos name e tradePolicy como publico para leitura de forma nativa:

![image](https://user-images.githubusercontent.com/23402009/32009081-c820d102-b98c-11e7-955b-4ee73f612048.png)

**Comment by lowbeer** [comment]
entidade VN nao está sendo criada automaticamente pelo DS

**Comment by lowbeer** [comment]
indice no MD nao está sendo criado automaticamente

**Comment by ohmyguigs** [comment]
Na entidade SO tbm tem o campo country, que nao vem automaticamente e deveria ser publico para leitura

**Comment by guilhermebruzzi** [comment]
@dikssl Melhorar as tarefinhas

**Comment by dikssl** [comment]
[] portal - arquivo de customização inStore, template e path

[] license manager - conceder licença de vendedor pro e-mail do easy setup, criar com um nome genérico

[] pci gateway - criar gateway stone e usar chave de autenticação, habilitar dinheiro crédito e débito

[] usar a logística do e-commerce

[] postman, add css no e-commerce

[] e-mail para administrador com um registro da instalação e conduzindo ele pra fazer isso sozinho depois num whitelabel

**Comment by darlenedms** [comment]
Essa issue foi dividida em várias outras.
