### ISSUE TITLE
Criar função de criar vendedor e license manager

### ISSUE THREAD

**Issue by guilhermebruzzi** [vtex/instore#373]

**Comment by gabrielgalc** [comment]
A conta filha não pode mexer na conta pai. 
@guilhermebruzzi , mexe aê

**Comment by guilhermebruzzi** [comment]
Esperando apenas o @Abinader nos ajudar a "burlar" o cache do license manager pra tornar essa function viável

**Comment by guilhermebruzzi** [comment]
Fazer tbm pra remover os usuários e ver se talvez isso tudo possa ser só do lado do License Manager
