### ISSUE TITLE
Montar proposta pra Cielo Lio de applinking olhando os parametros deles

### ISSUE THREAD

**Issue by guilhermebruzzi** [vtex/instore#397]
Olhar a API de integração local deles: https://desenvolvedores.cielo.com.br/api-portal/pt-br/content/integracao-local-cielo-lio
E escrever um exemplo em: https://github.com/vtex/vtex-payment-test/blob/master/docs/acquirers.pt.md

**Comment by darlenedms** [comment]
https://docs.google.com/document/d/1iHpOcvtP38aj7Csp0mDP1Jm1DqIlSUOw33fSQej6W7Q/edit?usp=sharing
