### ISSUE TITLE
Adicionar bandeira e adquirente nos dados do pedido

### ISSUE THREAD

**Issue by guilhermebruzzi** [vtex/instore#494]
- [x] RN repassar `cardBrandName` e `acquirerName` pra SPA
- [x] Gateway (adicionar campo `defaultAcquirer`)
- [x] Stone (retornar `cardBrandName`)
- [x] Sitef (retornar `cardBrandName`)
- [x] Passar `defaultAcquirer` pro RN

**Comment by darlenedms** [comment]
- [ ] RN repassar `cardBrandName` e `acquirerName` pra SPA
- [ ] Gateway (adicionar campo `defaultAcquirer`)
- [ ] Stone (retornar `cardBrandName`)
- [ ] Sitef (retornar `cardBrandName`)
