### ISSUE TITLE
Consertar logica de alterar endereço na entrega

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/instore#527]
Hoje quando se altera um endereço alteramos o selected address, se ele for um endereço salvo anteriormente salvamos o novo por cima com o mesmo addresID.
Deveria haver uma logica, se mudou o cep, cria um address novo. (o chk vai salvar apenas os que estiverem selected na compra e os que ja foram salvos anteriormente)

**Comment by guilhermebruzzi** [comment]
Será feito junto com a issue: https://github.com/vtex/instore/issues/511
