### ISSUE TITLE
Fix menu desktop pós subida de scroll fixo

### ISSUE THREAD

**Issue by guilhermebruzzi** [vtex/instore#530]

**Comment by gabrielgalc** [comment]
![screen shot 2018-01-23 at 7 27 32 pm](https://user-images.githubusercontent.com/21203990/35301810-bc7aa2dc-0073-11e8-902d-b5d73a1cb485.png)
![screen shot 2018-01-23 at 7 27 40 pm](https://user-images.githubusercontent.com/21203990/35301811-bc969ac8-0073-11e8-877e-03cd3bd8fdcf.png)

Bebber, o account e a versão do app quebraram tb
