### ISSUE TITLE
[BUG] Manual price ghost is back

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/instore#541]
## Como reproduzir:

 - Adicionar um item no carrinho.
 - Clicar no item na lista do carrinho e ir pra pagina de detalhe dele.
 - Clicar numa recomendação qualquer para ir para a pagina de detalhes dela.
 - Clicar no botão escrito 'voltar para o carrinho' duas vezes.

Obs:. o botão no detalhe da recomendação deveria ser 'Adicionar no carrinho'.

O erro que ocorre é o famoso forbidden 403 de remover preço manual quando não tem preço manual. (de quebra se vc der refresh o item volta no orderForm sem preço, como se o remove price tivesse tirado o preço dele mesmo dando forbiden, o chk retorna ele com erro)

**Comment by guilhermebruzzi** [comment]
Duplicado em: https://github.com/vtex/instore/issues/491
