### ISSUE TITLE
Preparar a tech demo

### ISSUE THREAD

**Issue by guilhermebruzzi** [vtex/instore#628]

**Comment by dikssl** [comment]
https://drive.google.com/file/d/1biYvgoYVpqEzxMn9ojiNf1kCyf6gTAsZ/view?usp=sharing

https://drive.google.com/file/d/14KrE-BxmZxwjXGmepQvR4VX7ryGOk8Tz/view?usp=sharing

não considerem o inglês (rs) vai ser em português
